### PR TITLE
Add Django 1.10 support

### PR DESCRIPTION
**Pull request by dwaynebailey**
This just opens up installation and testing for 1.10.  No tests fail so I assume it's usable.  I drop Django 1.7 testing, there is one site in the code that has a `<= 1.7` fallback that I didn't remove.

### CODE REVIEW

**Comment by aidaho** [comment]
I was a tiny bit late with the same changes :)

**Comment by helderco** [comment]
Django 1.10 is failing for me: 

```
AttributeError: 'Settings' object has no attribute 'TEMPLATE_DIRS'
```

In `overextends_tags.py`, TEMPLATE_DIRS no longer exists.

**Comment by SableWalnut** [comment]
:+1:

**Comment by SableWalnut** [comment]
Django 1.10 seems to work on master, but not the `0.4.1` release for me.

**Comment by stephenmcd** [comment]
Thanks @dwaynebailey

**Comment by stephenmcd** [comment]
Just pushed latest 0.4.2 to PyPI.
